### ISSUE TITLE
Bug with Save All Attributes

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#393] opened 2016-08-19 09:55 UTC
If an attribute has no content, it should not show in Public View - this works fine if attributes are saved individually. However, the Save All Attributes option saves all attributes including empty ones, after which they appear in Public View.

**Comment by m-hope** [comment] 2016-08-27 21:47
Also need to check Author and Nomenclatural Info attributes are saved correctly, as sometimes they they don't get saved when the 'Save All' button is used.

**Comment by sat01a** [comment] 2016-09-02 00:12
https://upsource.ala.org.au/profiles/review/PRFLS-CR-107

**Comment by m-hope** [comment] 2016-09-06 03:32
After discussion with Zoe/Kevin, we need to rethink the whole approach to empty attributes... It is possible when you have mandatory attributes to have attributes that have no content (eg: https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/Cynoglossum... this profile belongs to a collection where there are strict attributes that are also marked as mandatory... on the public view the 'empty' attributes are not displayed, but in edit mode the mandatory attributes are visible).  A non-mandatory attribute in a particular profile should be handled in the same way... if it has a title, it needs to be stored, but if it has no content then it shouldn't be visible in the public view, only in edit mode.

It should also be possible to 'remove' attribute content and save that attribute as 'empty'.  Again, the now empty attribute should not be visible in public view, but in edit mode it will be visible as a reminder that there should be content. 

So the outcome is for this issue is not to generate an error message if there is an empty attribute when 'Save All' is clicked, but to store the attribute as empty and not display it in public view.  We also need to consider allowing the Save button for an attribute that has been made empty.

**Comment by m-hope** [comment] 2016-09-07 23:37
Have confirmed the functionality of the Save All and Save buttons to be as follows:

When the Save All button is clicked:
 - Any attribute that has no title/name and no content will be ignored (ie: not saved)
 - Any attribute that has a title/name and the content has changed (regardless of whether there is content or not) will be saved and stored.
 - Any attribute that has content, but no title/name, will generate an error banner that indicates that all attributes must have a name.

To keep things consistent, the action of the Save button at the bottom of each attribute needs to match the conditions for the Save All button.  Ie: the Save button will appear if an attribute has been changed and has a valid title/name (regardless of whether there is content or not).  Note: if someone removes the content and the title/name of an attribute the Save button will remain greyed out (to achieve this functionality, the user should delete the attribute)

NOTE: this new functionality will require a change to how we display the Public View pages... any attribute that has a name but no content should not be visible/displayed in Public View.

**Comment by sat01a** [comment] 2016-09-09 04:51
https://upsource.ala.org.au/profiles/review/PRFLS-CR-112

**Comment by m-hope** [comment] 2016-09-14 04:55
Sorry guys, there is still a bug in this one... if you have an attribute that has a title and content and attempt to remove the content it will allow you to save this (either via Save or Save All buttons), but the attribute is then displayed in Public View with {} as the content.  eg: see: https://profiles.ala.org.au/opus/alatest/profile/Acacia%20abrupta

Also this problem seems to be affecting the case where I create an attribute and give it content but no title... it correctly gives an error if I try and use the Save All button, but if I then remove the content for that unnamed attribute (ie: it is now an unnamed and empty attribute and should be ignored or not saved), I will still get the title is mandatory error if I hit the Save All button again.

**Comment by m-hope** [comment] 2016-11-24 23:51
Related to #428

**Comment by sbearcsiro** [comment] 2016-11-29 08:05
https://upsource.ala.org.au/profiles/review/PRFLS-CR-117

**Closed** 2016-12-20 05:21 UTC
Labels: bug
