### ISSUE TITLE
Script errors when reordering bibliography

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/profile-hub#273] opened 2016-03-01 01:24 UTC
To reproduce:
1. Navigate to http://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/Acacia%20dealbata/update
2. Go to the bibliography section and re-order one of the items.
3. Press "Save"

The changes will save correctly, but after the save is complete an error "TypeError: Cannot read property 'clearCustomData' of null" will be displayed on the console and further actions will not work.

**Comment by ben3000** [comment] 2016-06-20 03:45
Duplicate of issue #372.

**Closed** 2016-06-29 03:19 UTC
Labels: bug
