### ISSUE TITLE
snapshot - created one but couldn't download and error occurred by used DOI hyperlink. Unable to test versions

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#192] opened 2015-11-16 01:13 UTC
http://www.bugherd.com/projects/58735/tasks/134

**Comment by ala-bugherd** [comment] 2015-11-16 05:08
Is this the same issue as http://www.bugherd.com/projects/58735/tasks/125? If so, it should be fixed now.

**Comment by m-r-c** [comment] 2015-11-16 05:09
Duplicate of #183

**Comment by ala-bugherd** [comment] 2015-11-16 22:57
Not the same as 125: this is caused by a permissions error when downloading the file.

**Comment by m-r-c** [comment] 2015-11-16 22:58
The download link for the PDF goes directly to profile-service, but has no API key. Either remove the API key check from the download action, or proxy the call through profile-hub.

**Comment by m-r-c** [comment] 2015-11-17 01:33
Fixed: skipping the API key check on publication downloads.

**Closed** 2015-11-17 01:33 UTC
Labels: bug, UAT
